title: Juhbol Book
# email:
description: >
  This is Juhbol's notebook, where they record useful docs and interesting stories.

url: "https://juhbol.github.io"

minima:
  skin: auto
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github, username: Juhbol, user_url: "https://github.com/Juhbol" }
    - { platform: rss, username: "RSS feed", user_url: "feed.xml" }

show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Use post title as their file name in the directory
permalink: /:title/

# Markdown parser settings
markdown    : kramdown
highlighter : rouge
kramdown:
  input: GFM
  math_engine: mathjax

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
